######################################################################################
# +--------------------------------------------------------------------------------+ #
# |                                                                                | #
# |              The Advanced Lightweight Minecraft Punishment Plugin              | #
# |                                                                                | #
# |                               Configuration File                               | #
# |                                                                                | #
# |                                                                                | #
# | GITHUB: https://github.com/Coadon/ALMPP                                        | #
# +--------------------------------------------------------------------------------+ #
######################################################################################

# This config file is automatically generated by the plugin.
# ALMPP - Copyright (c) 2020-2022 Coadon.

# New options are not added to this file automatically. Default values are used if an option cannot be found.

# For features using the Kyori adventure MiniMessage API, you can find formatting docs on https://docs.adventure.kyori.net/minimessage/format.

# ==================== NAME BAN vs. IP BAN ====================
# There are two types of banning in Minecraft:
# one is name ban, and the other one is ip ban. Each having their very own blacklist.
#
# Name ban blacklists a player by their Universal-Unique-Identifier (UUID). They don't store the player's IGN as they can change.
# On the other hand, IP ban blacklists a player by their Internet-Protocol-Address (IP Address).
#
# Name bans can be run using /ban or /tempban, while IP bans uses /banip or /tempbanip.
# =============================================================

# The default punishment reason.
#
# - When a player is punished without the issuer specifying a reason, this reason will be used.
default-punish-reason: "The Ban Hammer had spoken."

# No reason alternative.
#
# - Leaving the no-reason-alt as the punishment reason will cause the default-punish-reason to be used.
# - Leaving this empty disables this feature.
no-reason-alt: "#"

# Punishment reason auto-completion.
#
# - These reasons will appear as tab completion when writing a punishment command.
# - This feature is disabled by default. Uncomment if needed.
common-punish-reasons:
#  - "Cheat Detection."
#  - "Spamming in chat."
#  - "Bullying players."
#  - "Abusing server exploits."


# +--------------------------------------------------------------------------------+ #
# +                             Announcement Messages                              + #
# +--------------------------------------------------------------------------------+ #
# When a player is punished, a broadcast will be made for all online players.
# The below options determines the broadcast message.
#
# - Weather to enable this feature generally
enable-announcements: true
#
# - This feature uses the Kyori adventure MiniMessage API, formatting reference is above.
# - Leave any option(s) empty to disable it.
# - Use the [player] placeholder for the punished player's name.
punish-announcement:

  # When a player is punished with /ban or /tempban
  ban:
    - "<bold><color:red>Player [player] has been banned from this server."

  # When a player is kicked with /kick
  removal:
    - "<bold><color:red>Player [player] has been removed from this server."


# +--------------------------------------------------------------------------------+ #
# +                                  Ban Screens                                   + #
# +--------------------------------------------------------------------------------+ #
# Customize the contents of the ban screens below -- things that displays when a player is banned.
#
# - This feature uses the Kyori adventure MiniMessage API, formatting reference is above.
# - Each ban screen has its own set of placeholders.
ban-screens:

  # Permanent Ban with /ban
  # [reason] - The punishment reason
  # [date] - The date of issue
  permanent-name-ban:
    - "<color:red>You are permanently banned from this server!"
    - ""
    - "<color:gray>Reason: <color:white>[reason]"

  # Temporary Ban with /tempban
  # [reason] - The punishment reason
  # [date] - The date of issue
  # [expiry] - The expire date
  # [duration] - The remaining duration of the ban
  temporary-name-ban:
    - "<color:red>You are temporarily banned for <color:white>[duration]<color:red> from this server!"
    - ""
    - "<color:gray>Reason: <color:white>[reason]"

  # Permanent IP Ban with /banip
  # [reason] - The punishment reason
  # [date] - The date of issue
  permanent-ip-ban:
    - "<color:red>You are permanently banned from this server!"
    - ""
    - "<color:gray>Reason: <color:white>[reason]"

  # Temporary IP Ban with /tempbanip
  # [reason] - The punishment reason
  # [date] - The date of issue
  # [expiry] - The expire date
  # [duration] - The remaining duration of the ban
  temporary-ip-ban:
    - "<color:red>You are temporarily banned for <color:white>[duration]<color:red> from this server!"
    - ""
    - "<color:gray>Reason: <color:white>[reason]"

  # Kick with /kick
  # [reason] - The punishment reason
  # [date] - The date of issue
  removal:
    - "<color:red>You are kicked from this server!"
    - ""
    - "<color:gray>Reason: <color:white>[reason]"


### Optional Features

# Enable logging
#
# - Weather or not to log in the console when somebody got punished.
# - It will log regardless if the punishment is silent or not.
enable-logging: true

# Enable immunity
#
# - Weather or not to enable the feature that players with permission almpp.immune cannot be punished.
enable-immunity: false

# Debug mode.
#
# This feature is disabled by default to minimize verbose information that was sent to the console, enable it if you need to.
# This setting determines weather or not to print the stacktrace to the console when an error occurred while executing a command.
# This can be useful when trying to provide the error log when submitting a bug report.
debug-mode: false

# End of configuration file <- no, seriously. You are done.