name: ALMPP
version: '${version}'
main: com.coadon.almpp.almpp.ALMPP
api-version: 1.16
authors: [ Coadon ]
description: The Advanced Lightweight Minecraft Punish Plugin

commands:
  ban:
    description: Permanently bans a player from the server.
    permission: almpp.ban
    aliases: [ permban, pbn, bn, expel ]
    usage: /<command> <player> [reason]
  tempban:
    description: Temporarily bans a player from the server.
    permission: almpp.tempban
    aliases: [ tmpban, tbn, tb, texpel ]
    usage: /<command> <player> <duration> [reason]
  kick:
    description: Kicks a player from the server.
    permission: almpp.kick
    aliases: [ k, kp, ck, remove, rm ]
    usage: /<command> <player> [reason]
  kickall:
    description: Kicks every player from the server.
    permission: almpp.kickall
    aliases: [ kall, kap, ka ]
    usage: /<command> [reason]
  unban:
    description: Unbans player(s) from the blacklist.
    permission: almpp.pardon
    aliases: [ pardon ]
    usage: /<command> <player...>
  almpp:
    description: Displays information about this plugin.
    permission: almpp.plugininfo
    usage: /<command>

permissions:
  almpp.*:
    description: Wildcard permission for ALMPP.
    children:
      almpp.ban: true
      almpp.tempban: true
      almpp.kick: true
      almpp.kickall: true
      almpp.pardon: true
      almpp.plugininfo: true
  almpp.ban:
    description: Allow access to /ban command.
  almpp.tempban:
    description: Allow access to /tempban command.
  almpp.kick:
    description: Allow access to /kick command.
  almpp.kickall:
    description: Allow access to /kickall command.
  almpp.pardon:
    description: Allow access to /unban command.
  almpp.immune:
    description: Immune to all punishments except for kickall.
  almpp.plugininfo:
    description: Allow access to /almpp command.
