name: ALMPP
version: '${version}'
main: com.coadon.almpp.ALMPP
api-version: 1.16
authors: [Coadon]
description: The Advanced Lightweight Minecraft Punish Plugin

commands:
  ban:
    description: Ban a player permanently
    usage: /<command> <player> [reason]
    permission: almpp.ban
    aliases: [permban, bn]
  banip:
    description: Ban a player permanently by IP
    usage: /<command> <player> [reason]
    permission: almpp.banip
    aliases: [permbanip, ban-ip, bnip]
  kick:
    description: Kick a player
    usage: /<command> <player> [reason]
    permission: almpp.kick
    aliases: [k, remove, rm]
  kickall:
    description: Kick all online players
    usage: /<command> [reason]
    permission: almpp.kickall
    aliases: [kall]
  tempban:
    description: Ban a player temporarily
    usage: /<command> <player> <duration> [reason]
    permission: almpp.tempban
    aliases: [tbn]
  tempbanip:
    description: Ban a player temporarily by IP
    usage: /<command> <player> <duration> [reason]
    permission: almpp.tempbanip
    aliases: [tempban-ip, tbnip]
  unban:
    description: Unban a player
    usage: /<command> <player...>
    permission: almpp.pardon
    aliases: [pardon]
  unbanip:
    description: Ban a player temporarily by IP
    usage: /<command> <player> <duration> [reason]
    permission: almpp.tempbanip
    aliases: [unban-ip, pardonip, pardon-ip]

permissions:
  almpp.*:
    default: op
    description: Wildcard permission for ALMPP.
  almpp.ban:
    description: Allow access to /ban command.
  almpp.banip:
    description: Allow access to /banip command.
  almpp.immune:
    description: Immune to all punishments except for kickall.
  almpp.kick:
    description: Allow access to /kick command.
  almpp.kickall:
    description: Allow access to /kickall command.
  almpp.tempban:
    description: Allow access to /tempban command.
  almpp.tempbanip:
    description: Allow access to /tempbanip command.
  almpp.unban:
    description: Allow access to /unban command.
