name: ALMPP
version: '${version}'
main: com.coadon.almpp.almpp.ALMPP
api-version: 1.13
authors: [ Coadon ]
description: The Advanced Lightweight Minecraft Punish Plugin

commands:
  ban:
    description: Permanently bans a player from the server.
    permission: almpp.ban
    aliases: [ acban, acb, banplayer, bnp, bn ]
    usage: /<command> <player> [reason]
  tempban:
    description: Temporarily bans a player from the server.
    permission: almpp.tempban
    aliases: [ actempban, actb, tempbanplayer, tbnp, tbn ]
    usage: /<command> <player> <duration> [reason]
  kick:
    description: Kicks a player from the server.
    permission: almpp.kick
    aliases: [ ackick, ack, kickplayer, kp, ck ]
    usage: /<command> <player> [reason]
  kickall:
    description: Kicks every player from the server.
    permission: almpp.kickall
    aliases: [ ackickall, acka, kickallplayers, kap, ka ]
    usage: /<command> [reason]
  afkkick:
    description: Kicks a player from the server in an afk kick manner.
    permission: almpp.afkkick
    aliases: [ acafkkick, acak, afkkickplayer, afkk ]
    usage: /<command> <player>
  warn:
    description: Warn a player with a message.
    permission: almpp.warn
    aliases: [ wrn, wr ]
    usage: /<command> <player> <message>
  notice:
    description: Notice a player with a message.
    permission: almpp.notice
    aliases: [ note, infop, ntice, nt ]
    usage: /<command> <player> <message>
  brdcstban:
    description: Toggle weather to broadcast when a player gets terminated or afk kicked.
    permission: almpp.brdcstban
    aliases: [ broadcastban, bcb ]
    usage: /<command> [on|off]
  almpp:
    description: Displays information about this plugin.
    usage: /<command>

permissions:
  almpp.*:
    description: Root permission for ALMPP.
    children:
      almpp.ban: true
      almpp.tempban: true
      almpp.kick: true
      almpp.kickall: true
      almpp.afkkick: true
      almpp.warn: true
      almpp.notice: true
      almpp.brdcstban: true
  almpp.ban:
    description: Permission to use the /ban command.
  almpp.tempban:
    description: Permission to use the /tempban command.
  almpp.kick:
    description: Permission to use the /kick command.
  almpp.kickall:
    description: Permission to use the /kickall command.
  almpp.afkkick:
    description: Permission to use the /afkkick command.
  almpp.warn:
    description: Permission to use the /warn command.
  almpp.notice:
    description: Permission to use the /notice command.
  almpp.brdcstban:
    description: Permission to use the /brdcstban command.
